name: Pull Request and Dispatch Action

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # This is a required field for CodeGuru

    - name: CodeGuru Security
      uses: aws-actions/codeguru-security@v1
      with:
        source_path: .
        aws_region: us-east-1
        fail_on_severity: Critical # Critical findings will fail the build
        
    - name: Print findings
      run: |
        ls -l
        cat codeguru-security-results.sarif.json

    - name: Upload review result
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: codeguru-security-results.sarif.json # Your results file will be named codeguru-security-results.sarif.json
