name: CodeGuru Security on PR Changes

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  codeguru_security:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Step 2: Fetch changed files in the PR
    - name: Get Changed Files
      id: changed-files
      run: |
        git diff --name-only origin/main...HEAD > changed_files.txt
        grep -E '\.(py|js|java)$' changed_files.txt || echo "No relevant changes"

    # Step 3: Install AWS CLI if not pre-installed
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    # Step 4: Run CodeGuru Security Scan
    - name: Run CodeGuru Security Scan
      if: steps.changed-files.outputs.result != ''
      run: |
        CHANGED_FILES=$(cat changed_files.txt | tr '\n' ' ')
        echo $CHANGED_FILES
