name: CodeGuru Security on PR Changes

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  codeguru_security:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Step 2: Fetch changed files in the PR
    - name: Find changed lines
      id: changed_lines
      uses: hestonhoffman/changed-lines@v1
      
    - name: Print changed lines
      run: echo ${{ steps.changed_lines.outputs.changed_lines }}
